# Generated by Django 5.0.6 on 2024-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "002_fix_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="groups",
            field=models.ManyToManyField(to="core.group"),
        ),
    ]
